### ISSUE TITLE
FEATURE: 缓存问题向量

### ISSUE THREAD

**Issue by xqbumu** [ConnectAI-E/Feishu-Vector-Knowledge-Management#2]
功能点：
1. 将生成的用户提问向量缓存至内存
2. 查询缓存，如果命中则使用缓存结果

**Comment by h1deOnBush** [comment]
![image](https://user-images.githubusercontent.com/31787936/233767285-cb1addca-ac3c-4e77-9c55-0d0131977ebf.png)
想问一下在这里加上embeddingCache，然后以msg为key，计算出的embedding为value可以吗

**Comment by xqbumu** [comment]
> 

也是可以的，但是项目目前统计将缓存服务放在 pkg/services 下的，其下已经写有 vectorCache.go, 可以看情况修改并使用。

奥力给

**Comment by xqbumu** [comment]
> ![image](https://user-images.githubusercontent.com/31787936/233767285-cb1addca-ac3c-4e77-9c55-0d0131977ebf.png) 想问一下在这里加上embeddingCache，然后以msg为key，计算出的embedding为value可以吗

也是可以的，但是项目目前统计将缓存服务放在 pkg/services 下的，其下已经写有 vectorCache.go, 可以看情况修改并使用。

奥力给
